# ESTO ES UN COMENTARIO
# Todo lo que está a la derecha de # es solo para nosotros

version: 0.3.5 # NO TOCAR

# Configuración Global
html:
  title: Links |Adri # Este es el Título que aparece en la pestaña de navegador

# Colores de plantilla
theme:
  background_color: "#f9fafb"
  # cover_color: "#ff7070"

# Configuración Central
main:
  title:Adri # Aca podes poner tu nombre o el de tu producto

# Lista de bloques
blocks:
  # Estos bloques los podes editar cambiando SOLO el texto que está en blanco
  # Si querés eliminar una red social es tan facil como borrar los 3 campos correspondientes (title, icon, url)


  - title: Github
    icon: github
    url: https://github.com/Poppy2020

  - title: Instagram
    icon: instagram
    url: https://www.instagram.com/adrianapista



 
# Guardá el archivo haciendo click en Commit Changes, abajo
